name: build-deploy.yaml
on: push
jobs:
 build:
  outputs:
   deploy_output: ${{ steps.step1.outputs.version }}
  runs-on: ubuntu-latest
  steps:
   - name: This is build step
     id: step1
     run: echo "version=1.0.1" >> $GITHUB_OUTPUT
   - name: step two
     run: echo "This program version is ${{ steps.step1.outputs.version }}"
 deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
   - name: This is a deploy job
     run: echo "We would be deployig this with version ${{ needs.build.outputs.deploy_output }}"
