name: input-demo
on: 
 workflow_dispatch:
  inputs:
   environment:
    description: name of environment
    required: true
    default: dev
    options:
     - dev
     - test
     - prod
   artifact_tag:
    description: name of artifact
    required: true
   
jobs:
 inputs-demo:
  runs-on: ubuntu-latest
  steps:
  - name: provide details
    runs: echo "deploying with ${{ inputs.artifact_tag }} to ${{ inputs.environment }}"
