name: input-demo
on: 
 workflow_dispatch:
  inputs:
   environment:
    description: name of environment
    required: true
    default: dev
    options:
     - dev
     - test
     - prod
   artifact_tag:
    description: name of artifact
    required: true
   
jobs:
 inputs-demo:
  runs-on: ubuntu-latest
  steps:
  - name: provide details
    run: echo "deploying with ${{ inputs.artifact_tag }} to ${{ inputs.environment }}"
 context-demo:
  runs-on: ubuntu-latest
  steps:
  - name: use context variables
    run: |
     echo "This workflow is triggrered by ${{ github.actor }}
     echo "This workflow is triggrered by ${{ github.repository }}
  - name: print all variables under github context
    run: echo "{{ toJson(github) }}"
  - name: print enviroment variables
    run: echo "$GITHUB_SHA"
     
    
